### ISSUE TITLE
Add seed argument for running image training

### ISSUE THREAD

**Issue by darshit-desai** [Sharath-girish/Shacira#4]
I faced an error while running the main_image.py code that `args.seed` was not supplied, I am not sure the following argument value for seed is correct or not, but I used the following command to run:
```BASH
python3 app/image/main_image.py --config app/image/configs/kodak.yaml --dataset-path /path/to/dataset/Shacira/Kodak/ --seed 1
```
Error without `args.seed`:

```BASH
python3 app/image/main_image.py --config app/image/configs/pearl.yaml --dataset-path /home/datasetpath/ 
Traceback (most recent call last):
  File "/home/path/Research/Darshit/personal/828i_project/Shacira/app/image/main_image.py", line 512, in <module>
    set_seed(args.seed)
  File "/path/main_image.py", line 502, in set_seed
    torch.manual_seed(seed)
  File "/home/path/miniconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/random.py", line 36, in manual_seed
    seed = int(seed)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Sharath-girish** [comment]
Updated in commit 37b1a7b, thanks!
